# Short test training configuration to verify model works before full training
# Run with: python src/train.py --config=cfgs/convlstm_guillermo_v1_config.yaml --trainer=cfgs/trainer_test_short.yaml --data=cfgs/data_monotemporal_full_features.yaml --data.batch_size 15 --data.load_from_hdf5 true --data.data_dir ../data/hdf5

accelerator: gpu
strategy: auto
devices: 1
num_nodes: 1
precision: 32-true
logger: 
  class_path: pytorch_lightning.loggers.wandb.WandbLogger
  init_args:
    project: wildfire_progression
    log_model: false  # Don't save model to wandb for test run
callbacks: 
  - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
    init_args:
      monitor: val_ap
      mode: max
      save_top_k: 1
      filename: "test_convlstm_guillermo_v1_{epoch:03d}_{val_ap:.4f}"
      save_last: false
      every_n_epochs: 1
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
fast_dev_run: false
max_epochs: 5  # Only 5 epochs for quick test
min_epochs: 1
max_steps: -1
min_steps: -1
max_time: null
limit_train_batches: 0.2  # Only use 20% of training data
limit_val_batches: 0.3    # Only use 30% of validation data
limit_test_batches: 0.3   # Only use 30% of test data
limit_predict_batches: null
overfit_batches: 0.0
val_check_interval: null
check_val_every_n_epoch: 1
num_sanity_val_steps: 2
log_every_n_steps: 10  # Log more frequently for short run
enable_checkpointing: true
enable_progress_bar: true
enable_model_summary: true
accumulate_grad_batches: 1
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
deterministic: false
benchmark: false
inference_mode: true
use_distributed_sampler: true
profiler: null
detect_anomaly: false
barebones: false
plugins: null
sync_batchnorm: false
reload_dataloaders_every_n_epochs: 0
default_root_dir: ./lightning_logs
