seed_everything: 0

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 5e-5
    weight_decay: 0.01


model:
  class_path: models.PrithviEO2Model.PrithviEO2Lightning
  init_args:
    n_channels: 0  # overwritten by LightningCLI before instantiation
    flatten_temporal_dimension: false
    pos_class_weight: 1.0  # placeholder, overwritten per fold
    loss_function: BCE
    freeze_backbone: true
    temporal_pooling: conv
    head_hidden_dim: 256
    prithvi_variant: "prithvi_eo_v2_600_tl"
    backbone_grad_checkpointing: true
    feature_fusion: sum
    backbone_lr_scale: 0.1
    unfreeze_backbone_blocks: 10
    backbone_indices: [7, 15, 23, 31]

data:
  return_metadata: true

do_train: true
do_test: true
do_predict: false
