seed_everything: 0

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 0.01

model:
  class_path: models.PrithviEO2Model.PrithviEO2Lightning
  init_args:
    # required by BaseModel schema (will be ignored by Prithvi code)
    n_channels: 40
    flatten_temporal_dimension: false
    pos_class_weight: 236

    # actual Prithvi args you care about
    loss_function: BCE
    freeze_backbone: false
    temporal_pooling: conv
    head_hidden_dim: 256
    prithvi_variant: "prithvi_eo_v2_300"
    num_frames: 5
    backbone_indices: [5, 11, 17, 23]

do_train: true
do_test: true
do_predict: false
