# True Paper Baseline - Matches original ConvLSTM from paper
# Should get ~0.35 AP like the original paper
# Uses BCE loss instead of Focal, and matches their exact setup

seed_everything: 0
optimizer: 
  class_path: torch.optim.Adam  # Original paper likely used Adam, not AdamW
  init_args:
    lr: 0.001
model:
  class_path: models.ConvLSTMLightning.ConvLSTMLightning  # Use the original baseline model
  init_args:
    n_channels: 40
    flatten_temporal_dimension: false
    pos_class_weight: 236
    img_height_width: [128, 128]
    kernel_size: [3, 3]
    num_layers: 1  # Original paper: 1 layer

do_train: true
do_test: true
do_predict: false
