# Stage 2 Ablation: SMALL CAPACITY
# Tests if the larger hidden dimensions [64,128,256] are driving performance
# Reduced to [32, 64, 128] - half the capacity
seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
model:
  class_path: models.ConvLSTM_Guillermo_v1.ConvLSTM_Guillermo_v1
  init_args:
    n_channels: 40
    flatten_temporal_dimension: false
    pos_class_weight: 236
    loss_function: "Focal"
    img_height_width: [128, 128]
    kernel_sizes: [[3, 3], [3, 3], [3, 3]]
    hidden_dims: [32, 64, 128]  # ABLATION: Half capacity
    num_layers: 3
    pyramid_scales: [1]
    use_attention: false
    use_residual: false
    dropout_rate: 0.1
    deep_supervision_weight: 0.0

do_train: true
do_test: true
do_predict: false
