# pytorch_lightning==2.0.1
seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-4
    weight_decay: 1.0e-2

model:
  class_path: models.TransformerCA.TransformerCA
  init_args:
        # n_channels is injected by train.py
    flatten_temporal_dimension: true
    loss_function: FocalDice
    d_model: 128
    nhead: 4
    num_layers: 3
    kernel_size: 3
    dropout: 0.3
    use_doy: false
    # n_leading_observations is injected by train.py
  
do_train: true
do_test: true
do_predict: false




