# Stage 2 Ablation: PAPER BASELINE with BCE (instead of Focal)
# Tests if Focal Loss explains the gap between 0.43 and original paper's 0.35
seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
model:
  class_path: models.ConvLSTM_Guillermo_v1.ConvLSTM_Guillermo_v1
  init_args:
    n_channels: 40
    flatten_temporal_dimension: false
    pos_class_weight: 236
    loss_function: "BCE"  # ABLATION: Use BCE instead of Focal
    img_height_width: [128, 128]
    kernel_sizes: [[3, 3]]
    hidden_dims: [64]
    num_layers: 1
    pyramid_scales: [1]
    use_attention: false
    use_residual: false
    use_groupnorm: false
    use_multiscale_head: false
    use_feature_refinement: false
    dropout_rate: 0.0
    deep_supervision_weight: 0.0

do_train: true
do_test: true
do_predict: false
